-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 19, 2017 at 10:58 AM
-- Server version: 5.5.43-0ubuntu0.14.04.1
-- PHP Version: 5.6.30-12~ubuntu14.04.1+deb.sury.org+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `data`
--

-- --------------------------------------------------------

--
-- Table structure for table `airrail`
--

CREATE TABLE IF NOT EXISTS `air` (
  `agency_id` varchar(20) CHARACTER SET latin1 NOT NULL COMMENT 'Unique agency ID (preferably IATA number or similar)',
  `pax_id` varchar(11) CHARACTER SET latin1 NOT NULL COMMENT 'Unique lead pax ID generated by the back office',
  `booking_id` varchar(20) CHARACTER SET latin1 NOT NULL COMMENT 'Unique booking, consultation or file number created by the back office system',
  `ar_trans_id` varchar(10) CHARACTER SET latin1 NOT NULL COMMENT 'Unique transaction number within the booking or consultation',
  `agt_id` varchar(10) DEFAULT NULL,
  `ar_tran_date` date DEFAULT NULL COMMENT 'Date that the transaction was created in format of DDMMYYYY',
  `ar_tran_time` varchar(8) CHARACTER SET latin1 DEFAULT NULL COMMENT 'Time that the transaction was created in format of HHMM',
  `ar_mode` varchar(1) CHARACTER SET latin1 NOT NULL COMMENT 'Air = A, Rail = R',
  `ar_oper` varchar(10) CHARACTER SET latin1 NOT NULL COMMENT 'Operator ID generated by the back office',
  `ar_flight_num` varchar(7) CHARACTER SET latin1 NOT NULL COMMENT 'Flight number or train number to include, if available, the 2 letter airline or train operator ID ',
  `ar_class` varchar(1) CHARACTER SET latin1 NOT NULL COMMENT 'Air Economy = E, Air Premium = P, Air Business = B, Air & Rail First = F, Rail Standard = S',
  `ar_dep_date` date DEFAULT NULL COMMENT 'Departure date in format of DDMMYYYY',
  `ar_arr_date` date DEFAULT NULL COMMENT 'Arrival date in format of DDMMYYYY',
  `ar_dep_city` varchar(8) CHARACTER SET latin1 NOT NULL COMMENT '3 letter departure airport or station',
  `ar_arr_city` varchar(8) CHARACTER SET latin1 NOT NULL COMMENT '3 letter arrival airport or station',
  `ar_dep_time` varchar(8) CHARACTER SET latin1 NOT NULL COMMENT 'Departure time in format of HHMM',
  `ar_arr_time` varchar(8) CHARACTER SET latin1 NOT NULL COMMENT 'Arrival time in format of HHMM',
  `arr_maj_orig` varchar(8) CHARACTER SET latin1 NOT NULL,
  `ar_maj_dest` varchar(8) CHARACTER SET latin1 NOT NULL COMMENT '3 letter code of main destination or turnaround point',
  `ar_base_val` float NOT NULL COMMENT 'Total value of base fare incl decimal',
  `ar_tax_val` float NOT NULL COMMENT 'Total value of taxes incl decimal',
  `ar_ttl_comm` float DEFAULT NULL COMMENT 'Total value of commission earned including decimal',
  `ar_tkt_num` varchar(20) CHARACTER SET latin1 NOT NULL COMMENT 'Flight ticket number issued',
  `ar_conf_num` varchar(20) CHARACTER SET latin1 NOT NULL COMMENT 'Rail confirmation number',
  `ar_exch` varchar(1) CHARACTER SET latin1 DEFAULT NULL COMMENT 'If the ticket is an exchange this field must equal “Y”',
  `ar_exch_val` float DEFAULT NULL COMMENT 'Total value of additional collection including decimal (enter 0.00 if even exchange)',
  `ar_exch_orig` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'Original flight ticket number issued',
  `ar_hi_fare` float DEFAULT NULL COMMENT 'Value of the benchmark high fare including decimal',
  `ar_lo_fare` float DEFAULT NULL COMMENT 'Value of the benchmark low fare including decimal',
  `ar_reason` varchar(5) CHARACTER SET latin1 DEFAULT NULL COMMENT 'Value of the air reason code',
  `ar_inv_num` varchar(25) CHARACTER SET latin1 NOT NULL COMMENT 'Unique invoice number that was raised',
  `ar_pax_count` int(2) NOT NULL COMMENT 'Number of passengers associated with transaction (as available)',
  `acct_id` varchar(15) CHARACTER SET latin1 NOT NULL,
  `inv_val` float NOT NULL,
  `inv_tran_date` date DEFAULT NULL,
  UNIQUE KEY `CCTI_dep_dest` (`agency_id`,`pax_id`,`booking_id`,`ar_trans_id`,`ar_inv_num`,`ar_dep_city`,`ar_arr_city`),
  KEY `pax_id` (`pax_id`),
  KEY `cct` (`pax_id`,`booking_id`,`ar_trans_id`),
  KEY `acct_id` (`acct_id`),
  KEY `agency_acct_cct_index` (`agency_id`,`acct_id`,`pax_id`,`booking_id`,`ar_trans_id`),
  KEY `AcctId_TranDate` (`agency_id`,`ar_tran_date`,`ar_mode`,`acct_id`),
  KEY `agency_id` (`agency_id`(8)),
  KEY `agency-acct-mode` (`agency_id`,`acct_id`,`ar_mode`),
  KEY `agency_mode_confnum` (`agency_id`,`ar_mode`,`ar_conf_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
