-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 19, 2017 at 11:01 AM
-- Server version: 5.5.43-0ubuntu0.14.04.1
-- PHP Version: 5.6.30-12~ubuntu14.04.1+deb.sury.org+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `data`
--

-- --------------------------------------------------------

--
-- Table structure for table `head`
--

CREATE TABLE IF NOT EXISTS `head` (
  `agency_id` varchar(20) CHARACTER SET latin1 NOT NULL COMMENT 'Unique agency ID (preferably IATA number or similar)',
  `pax_id` varchar(11) CHARACTER SET latin1 NOT NULL COMMENT 'Unique lead pax ID generated by the back office',
  `booking_id` varchar(20) CHARACTER SET latin1 NOT NULL COMMENT 'Unique booking, consultation or file number created by the back office system',
  `acct_id` varchar(15) CHARACTER SET latin1 NOT NULL COMMENT 'Unique sales account ID or reference ',
  `branch_num` varchar(4) CHARACTER SET latin1 NOT NULL DEFAULT '' COMMENT 'Branch number or ID where the booking was originated',
  `agt_id` varchar(10) CHARACTER SET latin1 NOT NULL COMMENT 'The originating booking agent’s unique ID',
  `pax_title` varchar(10) CHARACTER SET latin1 NOT NULL,
  `pax_fname` varchar(30) CHARACTER SET latin1 NOT NULL COMMENT 'Lead passenger’s first name or initial',
  `pax_sname` varchar(30) CHARACTER SET latin1 NOT NULL COMMENT 'Lead passenger’s last name',
  `tran_date` date NOT NULL,
  `tran_time` varchar(8) CHARACTER SET latin1 NOT NULL,
  UNIQUE KEY `CCT_KEY` (`agency_id`,`pax_id`,`booking_id`),
  KEY `agency_id` (`agency_id`),
  KEY `acct_id` (`acct_id`),
  KEY `pax_booking_index` (`pax_id`,`booking_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
